from typing import Literal
from io import TextIOWrapper
from pathlib import Path
import re

from pybroma import Class

from broma_ida.metadata import __version__, PLUGIN_NAME
from broma_ida.broma.class_graph import ClassGraph
from broma_ida.broma.constants import BROMA_PLATFORMS
from broma_ida.class_builder.class_builder import ClassBuilder, STLClassBuilder

from ida_nalt import get_root_filename


FILE_HEADER = """// Generated by BromaIDA v{BROMAIDA_VERSION}, do not modify
#define {BROMAIDA_PLATFORM_MACRO_NAME}
// platform shorthands
#define BROMAIDA_IS_PLATFORM_MACHO {BROMAIDA_IS_PLATFORM_MACHO_VALUE}
#define BROMAIDA_IS_PLATFORM_ANDROID {BROMAIDA_IS_PLATFORM_ANDROID_VALUE}

#define STR_CONCAT_WRAPPER(a, b) a ## b
#define STR_CONCAT(a, b) STR_CONCAT_WRAPPER(a, b)
#define PAD(size) unsigned char STR_CONCAT(__pad, __LINE__)[size]\n\n"""  # noqa: E501


class BromaCodegen:
    """Codegen for Broma"""

    _classes: dict[str, Class]
    _target_platform: BROMA_PLATFORMS
    _types_path: Path
    _broma_path: Path

    _graph: ClassGraph
    _defined_classes: set[str]
    _enums_count: int

    def _emit_class(
        self,
        f: TextIOWrapper,
        cls: Class | None
    ):
        if cls is None or cls.name in self._defined_classes:
            return

        f.write(
            ClassBuilder(
                self._target_platform,
                cls,
                self._graph
            ).get_str()
        )

        self._defined_classes.add(cls.name)

    @staticmethod
    def _build_fwd_decl(name: str):
        if "::" in name:
            parts = name.split("::")
            bare = parts[-1]
            open_ns = " ".join(
                f"namespace {ns} {{" for ns in parts[:-1]
            )
            close_ns = (" }" * (len(parts) - 1))[1:]
            return f"{open_ns} class {bare}; {close_ns}\n"
        
        return f"class {name};\n"

    def __init__(
        self,
        platform: BROMA_PLATFORMS,
        broma_classes: dict[str, Class],
        types_path: Path,
        broma_path: Path
    ):
        self._target_platform = platform
        self._classes = broma_classes
        self._types_path = types_path
        self._broma_path = broma_path

        (self._types_path / "codegen").mkdir(parents=True, exist_ok=True)

    def write(self) -> Path:
        """
        Dumps codegenned classes, structs and enums
        to the path supplied in __init__ as a '.hpp' file
        named after the target platform and binary name.

        Returns:
            pathlib.Path
        """
        self._defined_classes = set()
        self._graph = ClassGraph(self._classes)
        self._file_path = self._types_path / "codegen" / f"{self._target_platform}-{get_root_filename().lower().split(".")[0]}.hpp"
        stl_builder = STLClassBuilder(self._graph.stl_type_definitions)

        with open(
            self._file_path,
            "w",
            buffering = 10 * 1024 * 1024
        ) as f:
            # Set up values used in .hpp for platform-specific definitions
            # TODO: move these to its own private function so we can properly work through
            # all the macros we need later for the upcoming SDK parser
            # OR, BromaImporter could add them on the fly to the final
            # file's content, so we could safely generate just once
            f.write(
                FILE_HEADER.format_map({
                    "BROMAIDA_VERSION": __version__,
                    "BROMAIDA_PLATFORM_MACRO_NAME":
                        self._get_bromaida_platform_macro(),
                    "BROMAIDA_IS_PLATFORM_MACHO_VALUE":
                        int(self._target_platform in ["imac", "m1", "ios"]),
                    "BROMAIDA_IS_PLATFORM_ANDROID_VALUE":
                        int(
                            self._target_platform in ["android32", "android64"]
                        )
                })
            )

            # Set up ready-made definitions for IDAClang to parse
            # _copy_content also populates _defined_classes from these files
            enums = (self._broma_path / "../include/Geode/Enums.hpp").resolve().as_posix()
            f.write(f'// Enums (dynamically included from "{enums}")\n')
            self._copy_content(f, enums, "enums_only", True)
            self._copy_content(f, "cocos2d.hpp", "parse")
            # I believe these would already come from either Extras.bro or FMOD.bro
            self._copy_content(f, "fmod.hpp")
            self._copy_content(f, "fmod_gd.hpp")
            # assumingly needed for IDA-specific shenanigans??
            self._copy_content(f, "helpers.hpp")

            f.flush()

            f.write("// typedefs\n")
            f.write("enum class TodoReturn {}; // Geode placeholder for unknown return types\n")
            f.write("\n")

            f.flush()

            # some classes from member/function argument/return types
            # need to be forward declared for them to work
            f.write("// Broma classes forward declarations\n")
            for class_name in self._graph.forward_declarations:
                f.write(self._build_fwd_decl(class_name))
            f.write("\n")

            f.flush()

            f.write("// STL type definitions part 1: Class types by pointer\n")
            # __BromaSTLTypesPtr
            f.write(stl_builder.emit_ptr_types())
            f.write("\n")

            f.flush()

            f.write("// Broma class definitions (in order of hard dependencies)\n")
            # get the right order of inheritance for importing classes
            # by-value member/function argument/return types come before their use
            for class_name in self._graph.class_order:
                cls = self._classes.get(class_name)
                self._emit_class(f, cls)
            f.write("\n")

            f.flush()

            f.write("// STL type definitions part 2: Class types by value\n")
            # __BromaSTLTypesValue
            f.write(stl_builder.emit_value_types())

        print(
            "[+] BromaCodegen: Wrote type definitions from "
            f"{self._enums_count} enums from 'Enums.hpp', "
            f"{len(self._defined_classes) - len(self._classes)} "
            "classes found from headers and "
            f"{len(self._classes)} Broma classes to "
            f"{self._file_path}"
        )
        return self._file_path

    def _copy_content(
        self, file: TextIOWrapper, fname: str,
        incl_mode: Literal["parse", "filter", "enums_only", ""] = "",
        no_header_comment: bool = False
    ):
        """
        Quick writes a file to another file.
        Also ensures content of the copied file
        are scanned for class definitions too.

        Args:
            file (TextIOWrapper): Target file to copy content into.
            fname (str): File name to copy content from.
            incl_mode (Literal["parse", "filter", "enums_only", ""]):
                Whether to parse includes, filter includes,
                only keep enum declarations, or do nothing.
            no_header_comment (bool):
                Whether not to comment down the name of the
                copied file in the target file.
                Defaults to False.
        """
        # detect if we have already passed an absolute path for the file
        src_path = Path(fname) if Path(fname).is_absolute() else (self._types_path / fname).resolve()

        with open(src_path) as fr:
            if not no_header_comment:
                file.write(f"// {fname}\n")

            content = {
                "filter": self._filter_relative_includes,
                "parse": self._parse_relative_includes,
                "enums_only": self._parse_enums_only,
                "": lambda t: t
            }[incl_mode](fr.readlines())

            file.writelines(content)
            file.write("\n\n")

            self._list_class_definitions(content)

    def _get_bromaida_platform_macro(self) -> str:
        """Gets the BromaIDA platform macro name."""
        plat_to_macro_suffix: dict[BROMA_PLATFORMS, str] = {
            "win": "WINDOWS",
            "imac": "INTEL_MACOS",
            "m1": "M1_MACOS",
            "ios": "IOS",
            "android32": "ANDROID32",
            "android64": "ANDROID64"
        }

        return f"""BROMAIDA_PLATFORM_{
            plat_to_macro_suffix[self._target_platform]
        }"""

    def _list_class_definitions(
        self,
        fcontent: list[str]
    ):
        scopes: list[tuple[str, str, int]] = []
        pending_namespace: str | None = None
        brace_depth = 0

        namespace_regex = re.compile(
            r"^\s*namespace\s+(\w+)\s*(\{)?"
        )

        class_regex = re.compile(
            r"^\s*(class|struct)\s+(\w+)"
        )

        for line in fcontent:
            if pending_namespace and line.lstrip().startswith("{"):
                scopes.append(
                    ("namespace", pending_namespace, brace_depth + 1)
                )
                pending_namespace = None

            if m := namespace_regex.match(line):
                if m.group(2):
                    scopes.append(
                        ("namespace", m.group(1), brace_depth + 1)
                    )
                else:
                    pending_namespace = m.group(1)

                continue

            if m := class_regex.match(line):
                kind, name = m.groups()

                inside_class = any(
                    scope_kind in ("class", "struct")
                    for scope_kind, _, _ in scopes
                )

                if not inside_class:
                    namespaces = [
                        scope_name
                        for scope_kind, scope_name, _ in scopes
                        if scope_kind == "namespace"
                    ]

                    self._defined_classes.add(
                        "::".join(namespaces + [name])
                    )

                scopes.append(
                    (kind, name, brace_depth + 1)
                )

            brace_depth += line.count("{")
            brace_depth -= line.count("}")

            while (
                scopes
                and brace_depth < scopes[-1][2]
            ):
                scopes.pop()

    def _filter_relative_includes(self, lines: list[str]) -> list[str]:
        """
        Comments out relative includes from a list of lines.

        Args:
            lines (list[str])

        Returns:
            list[str]
        """
        for i, e in enumerate(lines):
            if e.startswith('#include "'):
                lines[i] = f"// {lines[i]}"

        return lines

    def _parse_relative_includes(self, lines: list[str]) -> list[str]:
        """
        Parses all relative includes inside a list of lines
        and integrates them back into the lines.

        Args:
            lines (list[str])

        Returns:
            list[str]
        """
        for i, e in enumerate(lines):
            if e.startswith('#include "'):
                lines[i] = f"// {lines[i]}"

                include_path = e.split('"')[1]
                with open(self._types_path / include_path) as fr:
                    lines[i+1:i+1] = [*fr.readlines(), "\n\n"]

        return lines
    
    def _parse_enums_only(self, lines: list[str]) -> list[str]:
        """
        Extract only top-level enum declarations,
        ignoring everything inside #if blocks.
        This assumes the input is mostly sane
        to avoid a lot of edge cases.

        Args:
            lines (list[str])

        Returns:
            list[str]
        """
        out: list[str] = []

        macro_depth = 0
        enum_depth = 0
        in_enum = False
        enum_count = 0

        for line in lines:
            stripped = line.lstrip()

            # remove any #if/#ifdef/#ifndef blocks
            if stripped.startswith(("#if", "#ifdef", "#ifndef")):
                macro_depth += 1
                continue

            if stripped.startswith("#endif"):
                macro_depth -= 1
                continue

            if macro_depth or stripped.startswith("#"):
                continue

            if not in_enum:
                if not stripped.startswith("enum class "):
                    continue
                in_enum = True
                enum_count += 1

            out.append(line)

            enum_depth += line.count("{")
            enum_depth -= line.count("}")

            if enum_depth == 0 and ";" in line:
                in_enum = False

        self._enums_count = enum_count
        return out
