from typing import Literal
from io import TextIOWrapper
from pathlib import Path

from pybroma import Class, Root

from broma_ida.broma.constants import BROMA_PLATFORMS
from broma_ida.class_builder.class_builder import ClassBuilder
from broma_ida.utils import IDAUtils


class BromaCodegen:
    """Codegen for Broma"""

    FILE_HEADER = """// Generated by BromaIDA v{BROMAIDA_VERSION}, do not modify
#define {BROMAIDA_PLATFORM_MACRO_NAME}
// platform shorthands
#define BROMAIDA_IS_PLATFORM_MACHO {BROMAIDA_IS_PLATFORM_MACHO_VALUE}
#define BROMAIDA_IS_PLATFORM_ANDROID {BROMAIDA_IS_PLATFORM_ANDROID_VALUE}

#define STR_CONCAT_WRAPPER(a, b) a ## b
#define STR_CONCAT(a, b) STR_CONCAT_WRAPPER(a, b)
#define PAD(size) unsigned char STR_CONCAT(__pad, __LINE__)[size]\n\n"""  # noqa: E501

    _classes: dict[str, Class]
    _path: Path
    _target_platform: BROMA_PLATFORMS
    _broma_path: Path

    def __init__(
        self,
        platform: BROMA_PLATFORMS,
        broma_classes: dict[str, Class],
        path: Path,
        broma_path: Path
    ):
        self._target_platform = platform
        self._classes = broma_classes
        self._path = path
        self._broma_path = broma_path

        (self._path / "codegen").mkdir(parents=True, exist_ok=True)

    def write(self):
        """Dumps codegenned classes, structs and enums
        to the path supplied in __init__

        Args:
            path (Path)
        """
        with open(
            self._path / "codegen" / f"{self._target_platform}.hpp",
            "w",
            buffering=10 * 1024 * 1024,
        ) as f:
            f.write(
                self.FILE_HEADER.format_map({
                    "BROMAIDA_VERSION": IDAUtils.SCRIPT_VERSION,
                    "BROMAIDA_PLATFORM_MACRO_NAME":
                        self._get_bromaida_platform_macro(),
                    "BROMAIDA_IS_PLATFORM_MACHO_VALUE":
                        int(self._target_platform in ["imac", "m1", "ios"]),
                    "BROMAIDA_IS_PLATFORM_ANDROID_VALUE":
                        int(
                            self._target_platform in ["android32", "android64"]
                        )
                })
            )

            enums = (self._broma_path / "../include/Geode/Enums.hpp").resolve().as_posix()
            f.write(f'// Enums (dynamically included from "{enums}")\n')
            self._copy_content(f, enums, "enums_only", True)
            self._copy_content(f, "cocos2d.hpp", "parse")
            self._copy_content(f, "fmod.hpp")
            self._copy_content(f, "fmod_gd.hpp")
            self._copy_content(f, "helpers.hpp")

            f.flush()

            # now we codegen the Broma file
            f.write("// Broma\n\n")

            f.write("// typdefs\n")
            f.write("enum class TodoReturn {}; // :troll:\n")
            f.write("\n")

            f.flush()

            f.write("// class fwddec\n")
            for c in self._classes.keys():
                if "::" in c:
                    split_c = c.split("::")

                    if len(split_c) == 2:
                        f.write(
                            f"namespace {split_c[0]} {{ "
                            f"class {split_c[1]}; "
                            "}}\n"
                        )
                    elif len(split_c) == 3:
                        f.write(
                            f"namespace {split_c[0]} {{ "
                            f"namespace {split_c[1]} {{ "
                            f"class {split_c[2]};"
                            "}} "
                            "}}\n"
                        )
                else:
                    f.write(f"class {c};\n")
            f.write("\n")

            f.flush()

            f.write("// extras\n")
            for broma_class in Root(
                    str(self._broma_path / "Extras.bro")
            ).classes:
                f.write(
                    ClassBuilder(self._target_platform, broma_class).get_str()
                )
            f.write("\n")

            f.flush()

            f.write("// delegates and non-polymorphic classes\n")
            for _, broma_class in self._classes.items():
                if len(broma_class.superclasses) != 0:
                    continue

                f.write(
                    ClassBuilder(self._target_platform, broma_class).get_str()
                )
            f.write("\n")

            f.flush()

            f.write("// classes\n")
            for _, broma_class in self._classes.items():
                if len(broma_class.superclasses) == 0:
                    continue

                f.write(
                    ClassBuilder(self._target_platform, broma_class).get_str()
                )
            f.write("\n\n")

            f.flush()

            # Some STL types need declaration of either cocos2d or
            # broma classes, so we put this at the very bottom
            # of the codegenned header
            self._copy_content(f, "stl_types.hpp", "filter")

    def _copy_content(
            self, file: TextIOWrapper, fname: str,
            incl_mode: Literal["parse", "filter", "enums_only", ""] = "",
            no_header_comment: bool = False

    ) -> None:
        """Quick writes a file to another file

        Args:
            file (TextIOWrapper): File to write to
            fname (str): Filename to copy from
            incl_mode (Literal["parse", "filter", ""]):
                Whether to parse includes, filter includes,
                only keep enum declarations, or do nothing

        """
        # detect if we have already passed an absolute path for the file
        src_path = Path(fname) if Path(fname).is_absolute() else (self._path / fname)

        with open(src_path) as fr:
            if not no_header_comment:
                file.write(f"// {fname}\n")
            file.writelines({
                "filter": self._filter_relative_includes,
                "parse": self._parse_relative_includes,
                "enums_only": self._parse_enums_only,
                "": lambda t: t
            }[incl_mode](fr.readlines()))
            file.write("\n\n")

    def _get_bromaida_platform_macro(self) -> str:
        """Gets the BromaIDA platform macro name (shocker)"""
        plat_to_macro_suffix: dict[BROMA_PLATFORMS, str] = {
            "win": "WINDOWS",
            "imac": "INTEL_MACOS",
            "m1": "M1_MACOS",
            "ios": "IOS",
            "android32": "ANDROID32",
            "android64": "ANDROID64"
        }

        return f"""BROMAIDA_PLATFORM_{
            plat_to_macro_suffix[self._target_platform]
        }"""

    def _filter_relative_includes(self, lines: list[str]) -> list[str]:
        """Comments out relative includes from a list of lines

        Args:
            lines (list[str])

        Returns:
            list[str]
        """
        for i, e in enumerate(lines):
            if e.startswith('#include "'):
                lines[i] = f"// {lines[i]}"

        return lines

    def _parse_relative_includes(self, lines: list[str]) -> list[str]:
        """Parses and includes relative includes from a list of lines

        Args:
            lines (list[str])

        Returns:
            list[str]
        """
        for i, e in enumerate(lines):
            if e.startswith('#include "'):
                lines[i] = f"// {lines[i]}"

                include_path = e.split('"')[1]
                with open(self._path / include_path) as fr:
                    lines[i+1:i+1] = [*fr.readlines(), "\n\n"]

        return lines
    
    def _parse_enums_only(self, lines: list[str]) -> list[str]:
        """Extract only top-level enum declarations,
        ignoring everything inside #if blocks.
        This assumes the input is mostly sane
        to avoid a lot of edge cases.

        Args:
            lines (list[str])

        Returns:
            list[str]"""
        out: list[str] = []

        pp_depth = 0
        enum_depth = 0
        in_enum = False

        for line in lines:
            stripped = line.lstrip()

            # remove any #if/#ifdef/#ifndef blocks
            if stripped.startswith(("#if", "#ifdef", "#ifndef")):
                pp_depth += 1
                continue

            if stripped.startswith("#endif"):
                pp_depth -= 1
                continue

            if pp_depth or stripped.startswith("#"):
                continue

            if not in_enum:
                if not stripped.startswith("enum class "):
                    continue
                in_enum = True

            out.append(line)

            enum_depth += line.count("{")
            enum_depth -= line.count("}")

            if enum_depth == 0 and ";" in line:
                in_enum = False

        return out
